### ISSUE TITLE
OSError: [WinError 1455] 页面文件太小，无法完成操作

### ISSUE THREAD

**Issue by kalpa61** [zbf1991/WeCLIP#5]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda3\envs\wssam\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Anaconda3\envs\wssam\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\Anaconda3\envs\wssam\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Anaconda3\envs\wssam\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\Anaconda3\envs\wssam\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\Anaconda3\envs\wssam\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\Anaconda3\envs\wssam\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\PycharmProject\WeCLIP\scripts\dist_clip_voc.py", line 10, in <module>
    import torch
  File "D:\Anaconda3\envs\wssam\lib\site-packages\torch\__init__.py", line 124, in <module>
    raise err
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "D:\Anaconda3\envs\wssam\lib\site-packages\torch\lib\cudnn_cnn_infer64_8.dll" or one of its dependencies.
你好作者，我在运行python scripts/dist_clip_voc.py --config configs/voc_attn_reg.yaml命令时报错，提示我页面文件太小，无法完成操作，请问我应该如何修改才能正常运行

**Comment by kalpa61** [comment]
我已修复这个问题，在dist_clip_voc.py中找到num_workers，将其改为0或其他较小的值，另一种方法是增加你的anaconda安装磁盘的虚拟内存。
